"""transactions model

Revision ID: 30deee0b6fbb
Revises: cc68d43176df
Create Date: 2025-04-12 09:55:06.604992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30deee0b6fbb'
down_revision: Union[str, None] = 'cc68d43176df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorys', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorys', 'color')
    # ### end Alembic commands ###
