"""UserModel

Revision ID: a5e17f2b8501
Revises: ace0ac967c05
Create Date: 2025-04-11 14:21:54.939548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e17f2b8501'
down_revision: Union[str, None] = 'ace0ac967c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('salary', sa.Integer(), nullable=False))
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'salary')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
