"""Advice

Revision ID: efa4571dc6cc
Revises: 59ca9f525687
Create Date: 2025-04-11 21:48:01.219287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa4571dc6cc'
down_revision: Union[str, None] = '59ca9f525687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advices',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.Column('datetime_create', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advices')
    # ### end Alembic commands ###
